### PR TITLE
feat(plugins): add logging plugin that allows writing logs to storybook

### PR DESCRIPTION
**Pull request by buehler**
This adds a new plugin "logging".
This allows getting a log interface from the context to write
logs from buttons or actions. One can see the log list with the
"quote" icon and can inspect logged messages.

As an example:
```dart
Story(
  name: 'Story/Logging',
  builder: (context) => Center(
    child: ElevatedButton(
      onPressed: () => context.logger.log('This is a test message'),
      child: const Text('Log something'),
    ),
  ),
),
```

### CODE REVIEW

**Comment by buehler** [comment]
Alright, sorry @ookami-kb for the delay. I updated the golden images and pushed them.

Let me know if you need something :-)

**Comment by buehler** [comment]
Weird, why do they fail now?

**Comment by ookami-kb** [comment]
@buehler you can download generated images from the artifacts here: https://github.com/ookami-kb/storybook_flutter/actions/runs/8233183433?pr=131

In general, there are some minor incosistencies between different platforms, so it's better to just copy and commit the generated images from the artifacts, if they look correct.

**Comment by buehler** [comment]
@ookami-kb Wohow! :-)
Thank you for the help regarding the golden images.

**Review by ookami-kb — APPROVED** [review]

**Pull request merged**
